### ISSUE TITLE
Toggle Timer Button Broken

### ISSUE THREAD

**Issue by Vexxter9** [GTcreyon/SM63Redux#100]
**Describe the bug**
Pressing T does not toggle the timer

**To Reproduce**
Press T

**Expected behavior**
The timer toggles

**Screenshots**
Shouldn't be necessary

**System Information**
 - OS/Browser: Windows 10
 - Game version: v0.1.6.RC1
 - Other specs: My computer contains hardware

**Additional context**
No

**Comment by GTcreyon** [comment]
I think we removed that keybind, because it was obsoleted by the Show Timer option in the menu. We could re-implement it as a customizable binding, perhaps.

My thinking is that it may be worth adding both Show Timer and Reset Run to the binds menu, but have them unbound by default, so speedrunners can set them but they don't interfere with other players.
