### ISSUE TITLE
Conform player script to style guide

### ISSUE THREAD

**Issue by Koopa1018** [GTcreyon/SM63Redux#158]
**Describe the feature you'd like**
`player.gd` currently has all sorts of variables scattered all over the place. By contrast, the Godot style guide dictates that all `const`s, all `onready var`s, all public functions, all builtin functions, etc. be grouped together, with the groups appearing in a prescribed order. This would aid in script exploration--if I want to find the FLUDD sprite, I should be able to scan a single list of `onready var`s and know I'm seeing all possible options. 

**Do you intend to contribute this yourself? If so, how do you plan on doing it?**
I would be delighted to. The fix itself is just reordering lines, so it shouldn't be too demanding. That said, it'd have to be done when nobody has player-related PRs in progress, to ensure everything can merge nicely.

**Additional context**
N/A

**Comment by GTcreyon** [comment]
This was done because of the sheer volume of `const`s and `var`s in the player script, as well as the magnitude of the scroll distance between the top of the script and any given function. I think it would be more constructive to perform a general restructure of the script, rather than undo the bandaid fix and leave the wound open.
