### ISSUE TITLE
Mario behaves unusually when colliding with the sides of rocks

### ISSUE THREAD

**Issue by Expensure** [GTcreyon/SM63Redux#173]
**Describe the bug**

**To Reproduce**
Go to the end of the first room, keep walking at the spots in the screenshot.

**Expected behavior**
Mario should either stop or walk up the terrain.

**Screenshots**
![Dummyclip](https://user-images.githubusercontent.com/60733685/235353745-576990ee-9f1d-47fe-8fef-09bcb28234bc.png)

**System Information**
**OS/Browser:** Windows 10
**Game version:** v0.1.6 

Other specs: Not relevant
**Additional context**
Definitely looking like an if-statement not functioning on certain angles of slopes.

**Comment by Expensure** [comment]
![image](https://user-images.githubusercontent.com/60733685/235353885-4baf9068-a34e-4719-aead-2f4d1e2a05fe.png)
This rock in room two also seems to have an issue

**Comment by Kuma-Boo** [comment]
From what I can tell, the jittering seems to be mostly fixed in the latest master build. However, there're still some issues with ground detection-particularly with areas that have an acute collision surface.

Example 1 (Ground detection failure):
![image](https://github.com/GTcreyon/SM63Redux/assets/46894189/b9212a66-1ba1-4ad6-895c-e9e2db40ff2e)

Example 2 (Ground detection works, but is oddly delayed):
![image](https://github.com/GTcreyon/SM63Redux/assets/46894189/76d5700f-048d-4f29-b3a0-685175b58a76)

**Comment by GTcreyon** [comment]
> From what I can tell, the jittering seems to be mostly fixed in the latest master build. However, there're still some issues with ground detection-particularly with areas that have an acute collision surface.

In both examples, there are two steep slopes that meet at a vertex. There is no flat ground between them, so Godot does not treat it as a floor. Perhaps this should be considered a Godot bug? I tried to find info online about it, but couldn't.

In example 1, this is exactly what happens. No floor, so no standing state.

In example 2, Mario *would* fall endlessly, but I added a failsafe that forces Mario into a standing state if he has been stuck falling in place for half a second or so. This only applies when out of water.

I would very much like a real solution to this, but I couldn't think of one at the time. I'll try to find one when working on the rewrite, but I would also appreciate advice if anyone has any.

**Comment by GTcreyon** [comment]
Regarding the issue of jittering when walking into the base of a steep slope:

That's fixed in newer versions of the code, as @Kuma-Boo says. I'm not entirely sure what caused it, and the fix was accidental.

I would assume that it's to do with some old collision code that I used to bypass `move_and_slide()`'s speed changes on slopes - a quirk that newer Godot versions allow you to disable.

Mario probably walks into the slope, gets pushed up a bit, but then immediately falls down because he can't walk on the slope. The new version doesn't attempt to walk on the slope at all, instead treating it as a wall.

I will close this issue, since the jittering at the base of rocks (which was the original issue description) is fixed. However, I have opened #294 to track the intersecting-slopes issue.
